package com.lemick.fodmapscanner.model.api.model

import com.fasterxml.jackson.annotation.JsonProperty

   
data class Nutriments (

   @JsonProperty("calcium") var calcium : Double??,
   @JsonProperty("calcium_100g") var calcium100g : Double??,
   @JsonProperty("calcium_serving") var calciumServing : Double??,
   @JsonProperty("calcium_unit") var calciumUnit : String??,
   @JsonProperty("calcium_value") var calciumValue : Int??,
   @JsonProperty("carbohydrates") var carbohydrates : Double??,
   @JsonProperty("carbohydrates_100g") var carbohydrates100g : Double??,
   @JsonProperty("carbohydrates_serving") var carbohydratesServing : Int??,
   @JsonProperty("carbohydrates_unit") var carbohydratesUnit : String??,
   @JsonProperty("carbohydrates_value") var carbohydratesValue : Double??,
   @JsonProperty("cholesterol") var cholesterol : Int??,
   @JsonProperty("cholesterol_100g") var cholesterol100g : Int??,
   @JsonProperty("cholesterol_serving") var cholesterolServing : Int??,
   @JsonProperty("cholesterol_unit") var cholesterolUnit : String??,
   @JsonProperty("cholesterol_value") var cholesterolValue : Int??,
   @JsonProperty("energy") var energy : Int??,
   @JsonProperty("energy-kcal") var energyKcal : Int??,
   @JsonProperty("energy-kcal_100g") var energyKcal100g : Int??,
   @JsonProperty("energy-kcal_serving") var energyKcalServing : Int??,
   @JsonProperty("energy-kcal_unit") var energyKcalUnit : String??,
   @JsonProperty("energy-kcal_value") var energyKcalValue : Int??,
   @JsonProperty("energy_100g") var energy100g : Int??,
   @JsonProperty("energy_serving") var energyServing : Int??,
   @JsonProperty("energy_unit") var energyUnit : String??,
   @JsonProperty("energy_value") var energyValue : Int??,
   @JsonProperty("fat") var fat : Double??,
   @JsonProperty("fat_100g") var fat100g : Double??,
   @JsonProperty("fat_serving") var fatServing : Int??,
   @JsonProperty("fat_unit") var fatUnit : String??,
   @JsonProperty("fat_value") var fatValue : Double??,
   @JsonProperty("fiber") var fiber : Double??,
   @JsonProperty("fiber_100g") var fiber100g : Double??,
   @JsonProperty("fiber_serving") var fiberServing : Double??,
   @JsonProperty("fiber_unit") var fiberUnit : String??,
   @JsonProperty("fiber_value") var fiberValue : Double??,
   @JsonProperty("fruits-vegetables-nuts-estimate-from-ingredients_100g") var fruitsVegetableNutsEstimateIngredients100g : Int??,
   @JsonProperty("iron") var iron : Double??,
   @JsonProperty("iron_100g") var iron100g : Double??,
   @JsonProperty("iron_serving") var ironServing : Double??,
   @JsonProperty("iron_unit") var ironUnit : String??,
   @JsonProperty("iron_value") var ironValue : Double??,
   @JsonProperty("nova-group") var novaGroup : Int??,
   @JsonProperty("nova-group_100g") var novaGroup100g : Int??,
   @JsonProperty("nova-group_serving") var novaGroupServing : Int??,
   @JsonProperty("nutrition-score-fr") var nutritionScoreFr : Int??,
   @JsonProperty("nutrition-score-fr_100g") var nutritionScoreFr100g : Int??,
   @JsonProperty("proteins") var proteins : Double??,
   @JsonProperty("proteins_100g") var proteins100g : Double??,
   @JsonProperty("proteins_serving") var proteinsServing : Int??,
   @JsonProperty("proteins_unit") var proteinsUnit : String??,
   @JsonProperty("proteins_value") var proteinsValue : Double??,
   @JsonProperty("salt") var salt : Double??,
   @JsonProperty("salt_100g") var salt100g : Double??,
   @JsonProperty("salt_serving") var saltServing : Double??,
   @JsonProperty("salt_unit") var saltUnit : String??,
   @JsonProperty("salt_value") var saltValue : Int??,
   @JsonProperty("saturated-fat") var saturatedFat : Double??,
   @JsonProperty("saturated-fat_100g") var saturatedFat100g : Double??,
   @JsonProperty("saturated-fat_serving") var saturatedFatServing : Double??,
   @JsonProperty("saturated-fat_unit") var saturatedFatUnit : String??,
   @JsonProperty("saturated-fat_value") var saturatedFatValue : Double??,
   @JsonProperty("sodium") var sodium : Double??,
   @JsonProperty("sodium_100g") var sodium100g : Double??,
   @JsonProperty("sodium_serving") var sodiumServing : Double??,
   @JsonProperty("sodium_unit") var sodiumUnit : String??,
   @JsonProperty("sodium_value") var sodiumValue : Int??,
   @JsonProperty("sugars") var sugars : Double??,
   @JsonProperty("sugars_100g") var sugars100g : Double??,
   @JsonProperty("sugars_serving") var sugarsServing : Int??,
   @JsonProperty("sugars_unit") var sugarsUnit : String??,
   @JsonProperty("sugars_value") var sugarsValue : Double??,
   @JsonProperty("trans-fat") var transFat : Int??,
   @JsonProperty("trans-fat_100g") var transFat100g : Int??,
   @JsonProperty("trans-fat_serving") var transFatServing : Int??,
   @JsonProperty("trans-fat_unit") var transFatUnit : String??,
   @JsonProperty("trans-fat_value") var transFatValue : Int??,
   @JsonProperty("vitamin-a") var vitaminA : Double??,
   @JsonProperty("vitamin-a_100g") var vitaminA100g : Double??,
   @JsonProperty("vitamin-a_serving") var vitaminAServing : Double??,
   @JsonProperty("vitamin-a_unit") var vitaminAUnit : String??,
   @JsonProperty("vitamin-a_value") var vitaminAValue : Int??,
   @JsonProperty("vitamin-c") var vitaminC : Int??,
   @JsonProperty("vitamin-c_100g") var vitaminC100g : Int??,
   @JsonProperty("vitamin-c_serving") var vitaminCServing : Int??,
   @JsonProperty("vitamin-c_unit") var vitaminCUnit : String??,
   @JsonProperty("vitamin-c_value") var vitaminCValue : Int?

)